### ISSUE TITLE
Keycloak access issue when issuing USER_CREDENTIAL

### ISSUE THREAD

**Issue by aef24** [wistefan/deployment-demo#4]
Hello,
I have been deploying the different parts of the connector as described in the README.md. Keycloak is running correctly; however, when trying to access it to issue the USER_CREDENTIAL using the script, I encounter an error. I also cannot access the Keycloak page properly to issue the credentials. I am not sure if this is an issue with some part of the configuration. I would appreciate it if you could help me resolve this.

**Comment by aef24** [comment]
I am also getting errors in the provider pods when downloading the images:

<img width="989" height="319" alt="Image" src="https://github.com/user-attachments/assets/3442682d-3038-4a04-8d19-753b9daae458" />

**Comment by wistefan** [comment]
Hi, this very much looks like you are using an outdated version of the connector. Which version did you deploy?

**Comment by wistefan** [comment]
Could you provide me some details about the failed containers? Especially the one with the ImagePullBackoff. It looks very much like an issue that was solved in one of the previous connector version, thus my curiousity about the version.

Could you f.e. do: 
```shell
     export  KUBECONFIG=$(pwd)/target/k3s.yaml
     kubectl describe data-service-postgis-0 -n provider
```

**Comment by aef24** [comment]
Hi,

I checked the pod data-service-postgis-0 in the provider namespace, and here are the relevant events:

 ```
Normal Scheduled 3m default-scheduler Successfully assigned provider/data-service-postgis-0 to k3s
Normal Pulling 88s (x4 over 3m) kubelet Pulling image "docker.io/bitnami/postgresql:13.18.0"
Warning Failed 87s (x4 over 2m59s) kubelet Failed to pull image "docker.io/bitnami/postgresql:13.18.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/bitnami/postgresql:13.18.0": failed to resolve reference "docker.io/bitnami/postgresql:13.18.0": docker.io/bitnami/postgresql:13.18.0: not found
Warning Failed 87s (x4 over 2m59s) kubelet Error: ErrImagePull
Warning Failed 75s (x6 over 2m59s) kubelet Error: ImagePullBackOff
Normal BackOff 64s (x7 over 2m59s) kubelet Back-off pulling image "docker.io/bitnami/postgresql:13.18.0"
```


It seems that the image docker.io/bitnami/postgresql:13.18.0 cannot be found in Docker Hub, which is causing the ErrImagePull and then the ImagePullBackOff.

Could you confirm which connector version should be used here? It might indeed be related to the issue you mentioned in previous releases.

**Comment by wistefan** [comment]
Hi, the connector version should be 8.2.20. According to you describe, you must have an older version deployed, since the bitnami-image issue was solved for that release. Can you clean-up your environment completely(e.g. delete the k3s container) and reinstall again?

**Comment by aef24** [comment]
I have followed your suggestion and performed a complete cleanup of my environment:

- Deleted the K3s container and associated volumes.

- Reinstalled K3s from scratch.

- Removed the Helm repository data-space-connector and re-added it.

However, I am still encountering the same issues with several pods failing to start. For example, the current status of the pods is:
```
credentials-config-service-job-r5gqt 0/1 Error 0 2m2s
data-service-postgis-0 0/1 ImagePullBackOff 0 2m2s
data-service-scorpio-5847b8f955-v4pfq 0/1 Running 0 2m2s
dsconfig-9f76c5bf8-fth2p 1/1 Running 0 2m2s
odrl-pap-79757c5c95-5svlx 1/1 Running 2 (113s ago) 119s
postgresql-0 1/1 Running 0 2m2s
provider-dsc-apisix-control-plane-67c67dfcf6-tw6kj 0/1 Init:ErrImagePull 0 2m
provider-dsc-apisix-data-plane-6cd475bb7d-ctjxp 0/2 Init:ImagePullBackOff 0 2m1s
provider-dsc-etcd-0 0/1 ImagePullBackOff 0 2m2s
provider-dsc-etcd-1 0/1 ImagePullBackOff 0 2m2s
provider-dsc-etcd-2 0/1 ErrImagePull 0 2m2s
provider-dsc-keycloak-0 1/1 Running 0 2m2s

```

**Comment by aef24** [comment]
In addition, I cloned the official Data Space Connector repository from GitHub:

https://github.com/FIWARE/data-space-connector

and launched the local deployment using the most recent version.  

However, I am still encountering the same issues with several pods failing to start. The current status of the pods i also:

```
provider pod/data-service-postgis-0 0/1 ImagePullBackOff 0 17m
provider pod/data-service-scorpio-5764554d5b-75f57 0/1 Running 7 (3m7s ago) 17m
provider pod/did-helper-766866d7dd-gl7tp 1/1 Running 0 17m
provider pod/dsconfig-68d78966cc-rl7sz 1/1 Running 0 17m
provider pod/mongodb-5fbdcc8c64-spc24 1/1 Running 0 17m
provider pod/odrl-pap-84455bccfb-46hvn 1/1 Running 0 17m
provider pod/postgresql-0 1/1 Running 0 17m
provider pod/provider-apisix-control-plane-7b44d644bc-mnfkk 0/1 Init:ImagePullBackOff 0 17m
provider pod/provider-apisix-data-plane-79d6788c6b-9j8j5 0/2 Init:ImagePullBackOff 0 17m
provider pod/provider-biz-ecosystem-charging-backend-846656699f-2r5zt 1/1 Running 0 17m
provider pod/provider-biz-ecosystem-logic-proxy-0 1/1 Running 0 17m
provider pod/provider-etcd-0 0/1 ImagePullBackOff 0 17m
provider pod/provider-etcd-1 0/1 ImagePullBackOff 0 17m
provider pod/provider-etcd-2 0/1 ImagePullBackOff 0 17m

```
